config/routes.rb
Bufferheyo::Application.routes.draw do
  root to: "sessions#index"

  match 'profile', to: 'posts#new', as: 'profile', via: [:get, :post]
  match "auth/:provider/callback", to: "sessions#create", via: [:get, :post]
  match "auth/failure", to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  get 'past', to: 'posts#past', as: 'past'
  get 'settings', to: 'users#edit', as: 'settings'
  post 'settings', to: 'users#update'
  resources :posts
  resources :queue_time

  

end

app/models/post.rb
class Post < ActiveRecord::Base
  # has_attached_file :photo
  # validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/, allow_nil: true
  belongs_to :user

  def self.posting_past
    where("DATE(parse_time) < DATE(?)", Date.today)
  end

  def self.posting_today
    where("DATE(parse_time) = DATE(?)", Date.today)
  end

  def self.posting_tomorrow
    where("DATE(parse_time) = DATE(?)", Date.tomorrow)
  end

  def self.posting_future
    where("DATE(parse_time) > DATE(?)", Date.tomorrow)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def new
    @post = Post.new
    Time.zone = current_user.time_zone
    @startDate = Time.current
    @graph = Koala::Facebook::API.new(current_user.oauth_token)
    @page_names = []
    @page_names.push(["Post to newsfeed", 0])
    @pages = @graph.get_connections('me', 'accounts').each_with_index do |p, index|
      @page_names.push([p['name'], index + 1])
    end
  end

  def create
    @post = Post.new(post_params)
    @user = current_user
    @graph = Koala::Facebook::API.new(@user.oauth_token)
    Time.zone = @user.time_zone
    if post_params[:queue]
      if @post.save
        queued_posts = @user.posts.where(queue: true).where(posted: false)
        if queued_posts.any?
          @post.update_attribute(:queue_order, queued_posts.last.queue_order + 1)
        else
          @post.update_attribute(:queue_order, 1)
        end
        @post.update_attribute(:queue, true)
        @post.update_attribute(:user_id, @user.id)
        @user.update_queue_times
        if(post_params[:page_token].to_i == 0)
          @post.update_attribute(:page_name, "your newsfeed")
          job = Rufus::Scheduler.singleton.schedule_at @post.read_attribute(:parse_time).to_s do
            @graph = Koala::Facebook::API.new(@user.oauth_token)
            if(post_params[:photo] != "")
              @graph.put_picture(@post.photo, {message: @post.content}, "me")
            else
              @graph.put_connections("me", "feed", message: @post.content)
            end
          end
          @post.update_attribute(:job_id, job.id)
          flash[:success] = "You've queued a post on your newsfeed!"
          redirect_to profile_path
        else
          @page = @graph.get_connections('me', 'accounts')[post_params[:page_token].to_i - 1]
          @page_token = @page["access_token"]
          @page_name = @page["name"]
          @post.update_attribute(:user_id, @user.id)
          @post.update_attribute(:page_name, @page_name)
          logger.debug "Saved post with id #{@post.id}"
          logger.debug "#{@post.parse_time}"
          job = Rufus::Scheduler.singleton.schedule_at @post.read_attribute(:parse_time).to_s do
            @graph = Koala::Facebook::API.new(@page_token)
            if(post_params[:photo] != "")
              @graph.put_picture(@post.photo, {message: @post.content}, "me")
            else
              @graph.put_wall_post(@post.content)
            end
            logger.debug("Posted #{@post.content} at #{@post.buffer_time} buffer time > #{@post.parse_time}")
          end
          @post.update_attribute(:job_id, job.id)
          flash[:success] = "You've scheduled your post for #{@post.page_name} at #{@post.buffer_time}!"
          redirect_to profile_path
        end
      else
        flash[:error] = "Unfortunately, there was an error scheduling your post."
        redirect_to profile_path
      end
    else
      if(post_params[:page_token].to_i == 0)
        if @post.save
          @post.update_attribute(:user_id, @user.id)
          @post.update_attribute(:page_name, "your newsfeed")
          logger.debug "Saved post with id #{@post.id}"
          logger.debug "#{@post.parse_time}"
          job = Rufus::Scheduler.singleton.schedule_at @post.read_attribute(:parse_time).to_s do
            @graph = Koala::Facebook::API.new(@user.oauth_token)
            if(post_params[:photo] != "")
              @graph.put_picture(@post.photo, {message: @post.content}, "me")
            else
              @graph.put_connections("me", "feed", message: @post.content)
            end
            logger.debug("Posted #{@post.content} at #{@post.buffer_time} buffer time > #{@post.parse_time}")
          end
          @post.update_attribute(:job_id, job.id)
          flash[:success] = "You've scheduled a post on your newsfeed for #{@post.buffer_time}!"
          redirect_to profile_path
        else
          flash[:error] = "Unfortunately, there was an error scheduling your post."
          redirect_to profile_path
        end
      else
        @page = @graph.get_connections('me', 'accounts')[post_params[:page_token].to_i - 1]
        @page_token = @page["access_token"]
        @page_name = @page["name"]
        logger.debug "Pages: #{@page_token}"
        if @post.save
          @post.update_attribute(:user_id, @user.id)
          @post.update_attribute(:page_name, @page_name)
          logger.debug "Saved post with id #{@post.id}"
          logger.debug "#{@post.parse_time}"
          job = Rufus::Scheduler.singleton.schedule_at @post.read_attribute(:parse_time).to_s do
            @graph = Koala::Facebook::API.new(@page_token)
            if(post_params[:photo] != "")
              @graph.put_picture(@post.photo, {message: @post.content}, "me")
            else
              @graph.put_wall_post(@post.content)
            end
            logger.debug("Posted #{@post.content} at #{@post.buffer_time} buffer time > #{@post.parse_time}")
          end
          @post.update_attribute(:job_id, job.id)
          flash[:success] = "You've scheduled your post for #{@post.page_name} at #{@post.buffer_time}!"
          redirect_to profile_path
        else
          flash[:error] = "Unfortunately, there was an error scheduling your post."
          redirect_to profile_path
        end
      end
    end
  end

  def edit
    @post = Post.find(params[:id])
    Time.zone = current_user.time_zone
    @startDate = Time.current
    @graph = Koala::Facebook::API.new(@current_user.oauth_token)
    @page_names = []
    @page_names.push(["Post to newsfeed", 0])
    @pages = @graph.get_connections('me', 'accounts').each_with_index do |p, index|
      @page_names.push([p['name'], index + 1])
    end
  end

  def update
    @post = Post.find(params[:id])
    @user = current_user
    Time.zone = current_user.time_zone
    @graph = Koala::Facebook::API.new(@current_user.oauth_token)
    if Rufus::Scheduler.singleton.job(@post.read_attribute(:job_id)).nil?
      logger.debug "Nil Job"
      flash[:error] = "This post can no longer be edited!"
      redirect_to posts_path
      return
    end
    if(post_params[:page_token].to_i == 0)
      if @post.update(post_params)
        @post.update_attribute(:page_name, "your newsfeed")
        logger.debug "Updated post with id #{@post.id}"
        logger.debug "#{@post.parse_time}"
        Rufus::Scheduler.singleton.job(@post.read_attribute(:job_id)).unschedule
        job = Rufus::Scheduler.singleton.schedule_at @post.read_attribute(:parse_time).to_s do
          @graph = Koala::Facebook::API.new(@user.oauth_token)
          @graph.put_connections("me", "feed", message: @post.content)
          logger.debug("Posted #{@post.content} at #{@post.buffer_time}")
        end
        @post.update_attribute(:job_id, job.id)
        flash[:success] = "You've updated for post for your newsfeed at #{@post.buffer_time}!"
        redirect_to posts_path
      else
        flash[:error] = "Unfortunately, there was an error updating your post."
        redirect_to edit_post_path(params[:id])
      end
    else
      if @post.update(post_params)
        @page = @graph.get_connections('me', 'accounts')[post_params[:page_token].to_i - 1]
        @page_token = @page["access_token"]
        @page_name = @page["name"]
        @post.update_attribute(:page_name, @page_name)
        logger.debug "Pages: #{@page_token}"
        logger.debug "Updated post with id #{@post.id}"
        logger.debug "#{@post.parse_time}"
        Rufus::Scheduler.singleton.job(@post.read_attribute(:job_id)).unschedule
        job = Rufus::Scheduler.singleton.schedule_at @post.read_attribute(:parse_time).to_s do
          @graph = Koala::Facebook::API.new(@page_token)
          @graph.put_wall_post(@post.content)
          logger.debug("Posted #{@post.content} at #{@post.buffer_time} buffer time > #{@post.parse_time}")
        end
        @post.update_attribute(:job_id, job.id)
        flash[:success] = "You've updated for post for #{@post.page_name} at #{@post.buffer_time}!"
        redirect_to posts_path
      else
        flash[:error] = "Unfortunately, there was an error updating your post."
        redirect_to edit_post_path(params[:id])
      end
    end
  end

  def index
    Time.zone = current_user.time_zone
    @startDate = Time.current
    @posts_past = Post.posting_past.where(user_id: current_user.id).order(:parse_time)
    @posts_today = Post.posting_today.where(user_id: current_user.id).order(:parse_time)
    @posts_tomorrow = Post.posting_tomorrow.where(user_id: current_user.id).order(:parse_time)
    @posts_future = Post.posting_future.where(user_id: current_user.id).order(:parse_time)
  end

  def past
    Time.zone = current_user.time_zone
    @startDate = Time.current
    @posts_past = Post.posting_past.where(user_id: current_user.id).order(:parse_time)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:success] = "Post deleted!"
    redirect_to posts_path
  end

  private
    def post_params
      params.require(:post).permit(:queue, :content, :buffer_time, :parse_time, :photo, :page_token)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.haml
=form_for @post do |f|
  %div{style: "width: 500px;"}
    =f.label :content
    =f.text_field :content, class: "form-control"
    %br
    =f.label :page_token, "Post to"
    %br
    =f.select :page_token, @page_names
    ="Currently posting to " + @post.page_name
    %br
    %br
    =f.label :photo, "Photo URL"
    =f.text_field :photo, class: "form-control"
    / Ajax preview
    / #image_view
    /   =image_tag @post.photo.url
    %br
    =f.label :buffer_time
    %input.form-control{id: "post_buffer_time", name: "post[buffer_time]", "data-format" => "MM/dd/yyyy HH:mm:ss PP", :type => "text", value: @post.buffer_time}
    =f.hidden_field :parse_time
    %br
    =f.submit

:javascript
  $(function() {
    $('#post_buffer_time').datetimepicker({
      language: 'en',
      pick12HourFormat: true,
      startDate: new Date(#{@startDate.year}, #{@startDate.month - 1}, #{@startDate.day})
    });
  });

  $('#post_buffer_time').on("dp.hide", function(e){
    $('#post_parse_time').val($('#post_buffer_time').data("DateTimePicker").getDate());
  });

app/views/posts/index.html.haml
%h2
  Your queued posts
-if @posts_past.any?
  =link_to "View past posts", past_path
-if @posts_today.any?
  %h3
    Today
  %table.table.table-hover
    %thead
      %tr
        %th
          Content
        %th
          Time
        %th
          Location
        %th
          Edit
    %tbody
    -@posts_today.each do |post|
      %tr
        %td
          =post.content
        %td
          -if post.queue
            =post.parse_time
          -else
            =post.buffer_time
        %td
          =post.page_name.capitalize
        %td
          -if post.parse_time < @startDate
            %span.edit_link
              Posted
          -else
            %span.edit_link
              =link_to "Edit", edit_post_path(post)
              =link_to "Delete", post, method: :delete, data: { confirm: "Delete post for #{post.page_name}?" }
-if @posts_tomorrow.any?
  %h3
    Tomorrow
  %table.table.table-hover
    %thead
      %tr
        %th
          Content
        %th
          Time
        %th
          Location
        %th
          Edit
    %tbody
    -@posts_tomorrow.each do |post|
      %tr
        %td
          =post.content
        %td
          -if post.queue
            =post.parse_time
          -else
            =post.buffer_time
        %td
          =post.page_name.capitalize
        %td
          -if post.parse_time < @startDate
            %span.edit_link
              Posted
          -else
            %span.edit_link
              =link_to "Edit", edit_post_path(post)
              =link_to "Delete", post, method: :delete, data: { confirm: "Delete post for #{post.page_name}?" }
-if @posts_future.any?
  %h3
    Future
  %table.table.table-hover
    %thead
      %tr
        %th
          Content
        %th
          Time
        %th
          Location
        %th
          Change
    %tbody
    -@posts_future.each do |post|
      %tr
        %td
          =post.content
        %td
          -if post.queue
            =post.parse_time
          -else
            =post.buffer_time
        %td
          =post.page_name.capitalize
        %td
          -if post.parse_time < @startDate
            %span.edit_link
              Posted
          -else
            %span.edit_link
              =link_to "Edit", edit_post_path(post)
              =link_to "Delete", post, method: :delete, data: { confirm: "Delete post for #{post.page_name}?" }

app/views/posts/new.html.haml
/ ="OAuth expiration: " + current_user.oauth_expires_at.to_s
/ %br
/ ="Current time offset: " + Time.zone.now.utc_offset.to_s
/ %br
%h2
  Schedule your posts
=form_for @post do |f|
  %div{style: "width: 500px;"}
    =f.label :content
    =f.text_field :content, class: "form-control"
    %br
    =f.label :page_token, "Post to"
    %br
    =f.select :page_token, @page_names
    %br
    %br
    =f.label :photo, "Photo URL"
    =f.text_field :photo, class: "form-control"
    / Ajax preview
    / #image_view
    /   =image_tag @post.photo.url
    %br
    =f.label :buffer_time
    %input.form-control{id: "post_buffer_time", name: "post[buffer_time]", "data-format" => "MM/dd/yyyy HH:mm:ss PP", :type => "text"}
      / %span.input-group-addon
      /   %i{"data-time-icon" => "fa fa-clock-o", "data-date-icon" => "fa fa-calendar"}
    =f.hidden_field :parse_time
    =f.hidden_field :queue
    %br
    =f.submit "Create Post", onclick: "javascript:$('#post_queue').val(false);"
    =f.submit "Queue Post", onclick: "javascript:$('#post_queue').val(true);"

:javascript
  $(function() {
    $('#post_buffer_time').datetimepicker({
      language: 'en',
      pick12HourFormat: true,
      startDate: new Date(#{@startDate.year}, #{@startDate.month - 1}, #{@startDate.day})
    });
  });

  $('#post_buffer_time').on("dp.hide", function(e){
    $('#post_parse_time').val($('#post_buffer_time').data("DateTimePicker").getDate());
  });


app/views/posts/past.html.haml
%h2
  Past posts
%table.table.table-hover
  %thead
    %tr
      %th
        Content
      %th
        Time
      %th
        Location
      %th
        Edit
  %tbody
  -@posts_past.reverse_each do |post|
    %tr
      %td
        =post.content
      %td
        -if post.queue
          =post.parse_time
        -else
          =post.buffer_time
      %td
        =post.page_name.capitalize
      %td
        -if post.parse_time < @startDate
          %span.edit_link
            Posted
        -else
          %span.edit_link
            =link_to "Edit", edit_post_path(post)
            =link_to "Delete", post, method: :delete, data: { confirm: "Delete post for #{post.page_name}?" }