config/routes.rb
Bufferheyo::Application.routes.draw do
  root to: "sessions#index"

  match 'profile', to: 'posts#new', as: 'profile', via: [:get, :post]
  match "auth/:provider/callback", to: "sessions#create", via: [:get, :post]
  match "auth/failure", to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  get 'past', to: 'posts#past', as: 'past'
  get 'settings', to: 'users#edit', as: 'settings'
  post 'settings', to: 'users#update'
  resources :posts
  resources :queue_time

  

end

app/views/layouts/_flash.html.haml
-if flash.any?
  -flash.each do |name, msg|
    =msg

app/views/layouts/_header.html.haml
-if current_user
  %nav.navbar.navbar-default
    .container-fluid
      %a.navbar-brand{href: root_path}
        Buffer MVP
      %ul.nav.navbar-nav.navbar-right
        %li.navbar-text
          ="Welcome, " + current_user.name
        %li{class: "#{'navbar-active' if current_page?(profile_path)}"}
          =link_to "Home", profile_path
        %li{class: "#{'navbar-active' if current_page?(posts_path)}"}
          =link_to "Scheduled Posts", posts_path
        %li{class: "#{'navbar-active' if current_page?(settings_path)}"}
          =link_to "Settings", settings_path
        %li
          =link_to "Sign Out", signout_path, id: "sign_out"
-else
  %nav.navbar.navbar-default
    .container-fluid
      %a.navbar-brand{href: root_path}
        Buffer MVP
      %ul.nav.navbar-nav
        %li
          =link_to "Sign In With Facebook", "/auth/facebook", id: "sign_in"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bufferheyo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="wrap">
<%= render 'layouts/header' %>
<%= render 'layouts/flash' %>
<%= yield %>
</div>

</body>
</html>